import React from 'react';
import { motion } from 'framer-motion';
import { Wand2, Loader2, FileText, Download, Play } from 'lucide-react';

interface FixModePromptProps {
  isFixing: boolean;
  fixDiff: string | null;
  fixedFiles: Record<string, string>;
  isDownloadingRepo: boolean;
  onGenerateFix: () => void;
  onGetPatch: () => void;
  onDownloadZip: () => void;
  renderMarkdown: (content: string) => React.ReactNode;
}

export const FixModePrompt: React.FC<FixModePromptProps> = ({
  isFixing,
  fixDiff,
  fixedFiles,
  isDownloadingRepo,
  onGenerateFix,
  onGetPatch,
  onDownloadZip,
  renderMarkdown
}) => {
  return (
    <div className="mt-12 pt-12 border-t border-black/10 dark:border-white/10">
      <div className="flex flex-col gap-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-indigo-600 rounded-2xl flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <Wand2 className="w-7 h-7 text-white" />
            </div>
            <div>
              <h3 className="text-xl font-black text-zinc-900 dark:text-white uppercase tracking-tight">AI Fix Mode</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400 font-medium">Automatically identify and fix issues in this repository.</p>
            </div>
          </div>
          {!fixDiff && (
            <button
              onClick={onGenerateFix}
              disabled={isFixing}
              className="px-8 py-4 bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/50 text-white text-sm font-black rounded-2xl transition-all shadow-xl shadow-indigo-500/20 flex items-center justify-center gap-3 uppercase tracking-widest hover:scale-105 active:scale-95"
            >
              {isFixing ? <Loader2 className="w-5 h-5 animate-spin" /> : <Wand2 className="w-5 h-5" />}
              {isFixing ? 'Generating Fixes...' : 'Generate AI Fixes'}
            </button>
          )}
        </div>

        {fixDiff && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-zinc-50 dark:bg-zinc-950 border border-black/5 dark:border-white/5 rounded-3xl p-8"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 mb-8">
              <div>
                <h4 className="text-lg font-black text-zinc-900 dark:text-white uppercase tracking-tight">Proposed Changes</h4>
                <p className="text-sm text-zinc-500 dark:text-zinc-400 font-medium">Review the fixes generated by our AI agent.</p>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                <button
                  onClick={onGetPatch}
                  className="px-5 py-2.5 bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-800 text-zinc-900 dark:text-white text-xs font-black rounded-xl transition-all shadow-sm border border-black/10 dark:border-white/10 uppercase tracking-widest flex items-center gap-2"
                >
                  <FileText className="w-4 h-4" /> Get Patch
                </button>
                {Object.keys(fixedFiles).length > 0 && (
                  <div className="flex items-center gap-2">
                    <button
                      onClick={onDownloadZip}
                      disabled={isDownloadingRepo}
                      className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/50 text-white text-xs font-black rounded-xl transition-all shadow-lg shadow-indigo-500/30 uppercase tracking-widest flex items-center gap-2 hover:scale-105 active:scale-95"
                    >
                      {isDownloadingRepo ? (
                        <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                      {isDownloadingRepo ? 'Preparing Zip...' : 'Yes, Download Zip!'}
                    </button>
                  </div>
                )}
              </div>
            </div>
            <div className="prose prose-zinc dark:prose-invert max-w-none prose-pre:bg-zinc-950 prose-pre:border prose-pre:border-zinc-800/50 prose-pre:shadow-2xl prose-pre:rounded-2xl">
              {renderMarkdown(fixDiff)}
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
};
