
import { DOC_PHASE_INDICES } from '../constants';

export const generateMarkdown = (
  type: 'analysis' | 'documentation',
  parsedPhases: any[],
  currentAnalysis: any
) => {
  let markdown = '';

  // 1. Header Section
  markdown += `# ${type === 'analysis' ? 'Repository Analysis' : 'Technical Documentation'}: ${currentAnalysis.repoName}\n\n`;
  markdown += `> Generated by **GitRepoAnalyzer AI** on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n\n`;
  
  markdown += `## 📋 Overview & Purpose\n\n`;
  markdown += `This document provides a professional-grade ${type === 'analysis' ? 'analysis' : 'technical documentation'} of the **${currentAnalysis.repoName}** repository. It covers architectural patterns, code quality, security, performance, and operational workflows.\n\n`;
  markdown += `### 🎯 Core Vision\n\n`;
  markdown += `The primary goal of this repository is to provide a robust solution for its target domain. Through advanced static analysis, we have mapped out its architecture and evaluated its production readiness. This application is designed to solve complex challenges by leveraging modern software engineering principles and a scalable architecture.\n\n`;

  // 2. Table of Contents
  markdown += `## 📑 Table of Contents\n\n`;
  
  let phasesToRender = parsedPhases;
  if (type === 'documentation') {
    phasesToRender = parsedPhases.filter((_, index) => DOC_PHASE_INDICES.includes(index));
  }

  phasesToRender.forEach((phase, index) => {
    const cleanTitle = phase.title.replace(/^PHASE \d+:\s*/i, '').trim();
    const anchor = cleanTitle.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
    markdown += `- [${cleanTitle}](#${anchor})\n`;
  });
  
  if (type === 'analysis' && currentAnalysis.fileTree?.length) {
    markdown += `- [Repository File Structure](#repository-file-structure)\n`;
  }
  
  markdown += `\n---\n\n`;

  // 3. Render Phases
  phasesToRender.forEach((phase) => {
    const cleanTitle = phase.title.replace(/^PHASE \d+:\s*/i, '').trim();
    markdown += `## ${cleanTitle}\n\n`;
    
    // Clean content: remove scores and phase references
    let cleanContent = phase.content
      .replace(/\[Score:\s*\d+\/10\]/gi, '')
      .replace(/Phase Score:\s*\d+\/10/gi, '')
      .trim();
    
    markdown += `${cleanContent}\n\n`;
    markdown += `---\n\n`;
  });

  // 4. File Tree Section
  if (type === 'analysis' && currentAnalysis.fileTree?.length) {
    markdown += `## Repository File Structure\n\n`;
    markdown += `\`\`\`text\n${currentAnalysis.fileTree.join('\n')}\n\`\`\`\n\n`;
    markdown += `---\n\n`;
  }

  // 5. Footer
  markdown += `\n*This report was generated automatically. For more information or to re-analyze, visit [GitRepoAnalyzer AI](https://gitrepoanalyzer.com).*`;

  return markdown;
};

export const downloadMarkdown = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
