import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import mermaid from 'mermaid';
import { extractMermaid, removeMermaid } from '../components/MarkdownComponents';
import toast from 'react-hot-toast';
import { DOC_PHASE_INDICES } from '../constants';

export const generatePDF = async (
  type: 'analysis' | 'documentation',
  phaseIndices: number[] | undefined,
  parsedPhases: any[],
  currentAnalysis: any
) => {
  const loadingToast = toast.loading('Initializing PDF engine...');
  try {
    // Initialize mermaid for PDF
    mermaid.initialize({
      startOnLoad: false,
      theme: 'base',
      securityLevel: 'loose',
    });

    const pdf = new jsPDF('p', 'pt', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 40;
    const contentWidth = pageWidth - margin * 2;
    const contentHeightPerPage = pageHeight - margin * 2 - 40;

    let currentY = margin;

    const addFooter = (pageNumber: number) => {
      pdf.setPage(pageNumber);
      const footerY = pageHeight - 15;
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Page ${pageNumber}`, pageWidth - margin, footerY, { align: 'right' });
    };

    const ensureSpace = (height: number) => {
      if (currentY + height > pageHeight - margin - 20) {
        addFooter(pdf.getNumberOfPages());
        pdf.addPage();
        currentY = margin;
        return true;
      }
      return false;
    };

    const tempContainer = document.createElement('div');
    tempContainer.style.position = 'absolute';
    tempContainer.style.left = '-9999px';
    tempContainer.style.top = '0';
    tempContainer.style.width = '800px';
    tempContainer.style.backgroundColor = '#ffffff';
    tempContainer.style.padding = '0';
    tempContainer.style.margin = '0';
    tempContainer.style.boxSizing = 'border-box';
    document.body.appendChild(tempContainer);

    toast.loading('Creating cover page...', { id: loadingToast });

    // COVER PAGE
    const coverDiv = document.createElement('div');
    coverDiv.style.width = '800px';
    coverDiv.style.height = '1100px';
    coverDiv.style.display = 'flex';
    coverDiv.style.flexDirection = 'column';
    coverDiv.style.justifyContent = 'center';
    coverDiv.style.alignItems = 'center';
    coverDiv.style.textAlign = 'center';
    coverDiv.style.padding = '80px';
    coverDiv.style.background = '#ffffff';
    coverDiv.style.color = '#1e293b';
    coverDiv.style.boxSizing = 'border-box';
    coverDiv.style.border = '40px solid #f1f5f9';

    coverDiv.innerHTML = `
      <div style="margin-bottom: 60px; color: #4f46e5;">
        <svg width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
          <path d="M14 2v6h6"></path>
          <path d="M16 13H8"></path>
          <path d="M16 17H8"></path>
          <path d="M10 9H8"></path>
        </svg>
      </div>
      <div style="text-transform: uppercase; letter-spacing: 4px; font-size: 14px; font-weight: 800; color: #64748b; margin-bottom: 20px;">Technical Report</div>
      <h1 style="font-size: 56px; font-weight: 900; margin-bottom: 30px; letter-spacing: -2px; line-height: 1.1; color: #0f172a;">
        ${type === 'analysis' ? 'Repository Analysis' : 'Technical Documentation'}
      </h1>
      <div style="width: 80px; height: 4px; background: #4f46e5; margin-bottom: 40px;"></div>
      <p style="font-size: 28px; color: #334155; margin-bottom: 60px; font-weight: 600; max-width: 600px;">
        ${currentAnalysis.repoName}
      </p>
      <div style="margin-top: auto; border-top: 1px solid #e2e8f0; padding-top: 40px; width: 100%; display: flex; justify-content: space-between; align-items: flex-end;">
        <div style="text-align: left;">
          <p style="font-size: 12px; color: #94a3b8; text-transform: uppercase; font-weight: 800; margin-bottom: 5px;">Generated By</p>
          <p style="font-size: 16px; font-weight: 700; color: #1e293b;">GitRepoAnalyzer AI</p>
        </div>
        <div style="text-align: right;">
          <p style="font-size: 12px; color: #94a3b8; text-transform: uppercase; font-weight: 800; margin-bottom: 5px;">Date</p>
          <p style="font-size: 16px; font-weight: 700; color: #1e293b;">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
      </div>
    `;
    tempContainer.appendChild(coverDiv);
    
    const coverCanvas = await html2canvas(coverDiv, { scale: 1.5, useCORS: true });
    pdf.addImage(coverCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', 0, 0, pageWidth, pageHeight);
    addFooter(pdf.getNumberOfPages());
    pdf.addPage();
    currentY = margin;

    // REPOSITORY SUMMARY SECTION
    const aboutDiv = document.createElement('div');
    aboutDiv.style.padding = '40px';
    aboutDiv.style.width = '800px';
    aboutDiv.style.boxSizing = 'border-box';
    aboutDiv.innerHTML = `
      <h2 style="font-size: 32px; font-weight: 900; color: #0f172a; margin-bottom: 30px; border-bottom: 4px solid #4f46e5; padding-bottom: 15px; letter-spacing: -1px;">Executive Summary</h2>
      <div style="font-size: 16px; line-height: 1.8; color: #334155;">
        <p style="margin-bottom: 25px; font-size: 18px;">This document provides a professional-grade ${type === 'analysis' ? 'analysis' : 'technical documentation'} of the <strong>${currentAnalysis.repoName}</strong> repository. It is intended for developers, architects, and stakeholders to understand the codebase's structure, quality, and operational requirements.</p>
        
        <div style="background: #f8fafc; padding: 30px; border-radius: 20px; border: 1px solid #e2e8f0; margin-bottom: 30px;">
          <h3 style="font-size: 20px; font-weight: 800; color: #1e293b; margin-bottom: 15px;">Core Purpose & Vision</h3>
          <p style="margin-bottom: 0;">The primary goal of this repository is to provide a robust solution for its target domain. Through advanced static analysis, we have mapped out its architecture and evaluated its production readiness. This application is designed to solve complex challenges by leveraging modern software engineering principles and a scalable architecture.</p>
        </div>

        <h3 style="font-size: 22px; font-weight: 800; color: #1e293b; margin-top: 40px; margin-bottom: 20px;">Strategic Technical Highlights</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px;">
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0;">
            <p style="font-weight: 800; color: #1e293b; margin-bottom: 10px;">Architecture</p>
            <p style="font-size: 14px; color: #64748b; margin: 0;">Reconstructed from source code patterns to reveal the underlying design philosophy.</p>
          </div>
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0;">
            <p style="font-weight: 800; color: #1e293b; margin-bottom: 10px;">Security</p>
            <p style="font-size: 14px; color: #64748b; margin: 0;">In-depth audit identifying vulnerabilities, hardcoded secrets, and risk vectors.</p>
          </div>
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0;">
            <p style="font-weight: 800; color: #1e293b; margin-bottom: 10px;">Performance</p>
            <p style="font-size: 14px; color: #64748b; margin: 0;">Profiling of critical paths to identify bottlenecks and optimization opportunities.</p>
          </div>
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0;">
            <p style="font-weight: 800; color: #1e293b; margin-bottom: 10px;">Scalability</p>
            <p style="font-size: 14px; color: #64748b; margin: 0;">Assessment of the system's ability to handle increased load and future growth.</p>
          </div>
        </div>

        <div style="background: #f1f5f9; padding: 25px; border-radius: 16px; margin-bottom: 30px;">
          <h3 style="font-size: 18px; font-weight: 800; color: #1e293b; margin-bottom: 15px;">Primary Target Audience</h3>
          <p style="font-size: 14px; color: #475569; margin: 0;">This documentation is specifically curated for technical leads, full-stack engineers, and DevOps professionals who require a deep understanding of the system's operational mechanics and codebase structure.</p>
        </div>

        <h3 style="font-size: 22px; font-weight: 800; color: #1e293b; margin-top: 40px; margin-bottom: 20px;">Repository Metadata</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
            <p style="font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: 800; margin-bottom: 5px;">Repository Name</p>
            <p style="font-size: 16px; font-weight: 700; color: #1e293b; margin: 0;">${currentAnalysis.repoName}</p>
          </div>
          <div style="background: #ffffff; padding: 20px; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
            <p style="font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: 800; margin-bottom: 5px;">Analysis Timestamp</p>
            <p style="font-size: 16px; font-weight: 700; color: #1e293b; margin: 0;">${new Date(currentAnalysis.timestamp).toLocaleString()}</p>
          </div>
        </div>
      </div>
    `;
    tempContainer.innerHTML = '';
    tempContainer.appendChild(aboutDiv);
    const aboutCanvas = await html2canvas(aboutDiv, { scale: 1.5, useCORS: true });
    const aboutHeight = (aboutCanvas.height * contentWidth) / aboutCanvas.width;
    pdf.addImage(aboutCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, aboutHeight);
    currentY += aboutHeight + 30;

    // Filter Phases
    let phasesToRender = parsedPhases;
    if (phaseIndices && phaseIndices.length > 0) {
      phasesToRender = parsedPhases.filter((_, index) => phaseIndices.includes(index));
    } else if (type === 'documentation') {
      phasesToRender = parsedPhases.filter((_, index) => DOC_PHASE_INDICES.includes(index));
    }

    // Render all phases
    for (let i = 0; i < phasesToRender.length; i++) {
      const phase = phasesToRender[i];
      toast.loading(`Processing Phase ${i + 1}/${phasesToRender.length}...`, { id: loadingToast });
      
      // 1. Render Phase Title
      const titleDiv = document.createElement('div');
      titleDiv.style.padding = '30px 40px';
      titleDiv.style.width = '800px';
      titleDiv.style.boxSizing = 'border-box';
      const phaseTitle = phase.title.replace(/^Phase \d+:\s*/i, '');
      let scoreHtml = phase.score && type === 'analysis' ? `<div style="font-weight: 800; color: #4f46e5; margin-bottom: 15px; font-size: 16px; background: #eef2ff; padding: 8px 16px; border-radius: 9999px; display: inline-block;">Score: ${phase.score}/10</div>` : '';
      titleDiv.innerHTML = `
        <h2 style="font-size: 28px; font-weight: 900; color: #0f172a; margin-bottom: 15px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; letter-spacing: -0.5px;">
          ${type === 'analysis' ? `Phase ${parsedPhases.indexOf(phase) + 1}: ` : ''}${phaseTitle}
        </h2>
        ${scoreHtml}
      `;
      
      tempContainer.innerHTML = '';
      tempContainer.appendChild(titleDiv);
      const titleCanvas = await html2canvas(titleDiv, { scale: 1.5, useCORS: true });
      const titleHeight = (titleCanvas.height * contentWidth) / titleCanvas.width;
      ensureSpace(titleHeight);
      pdf.addImage(titleCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, titleHeight);
      currentY += titleHeight + 10;

      // 2. Split content into parts
      const contentParts = phase.content.split(/(```mermaid\n[\s\S]*?```|```[\s\S]*?```)/g);
      
      for (const part of contentParts) {
        if (!part.trim()) continue;

        if (part.startsWith('```mermaid')) {
          const chart = part.replace(/```mermaid\n([\s\S]*?)```/, '$1').trim();
          try {
            const { svg } = await mermaid.render(`mermaid-pdf-${i}-${Math.random().toString(36).slice(2, 7)}`, chart);
            const svgDiv = document.createElement('div');
            svgDiv.style.padding = '30px 40px';
            svgDiv.style.width = '800px';
            svgDiv.style.textAlign = 'center';
            svgDiv.style.boxSizing = 'border-box';
            svgDiv.innerHTML = svg;
            const svgEl = svgDiv.querySelector('svg');
            if (svgEl) {
              svgEl.style.maxWidth = '100%';
              svgEl.style.height = 'auto';
            }
            
            tempContainer.innerHTML = '';
            tempContainer.appendChild(svgDiv);
            const svgCanvas = await html2canvas(svgDiv, { scale: 1.5, useCORS: true });
            const svgHeight = (svgCanvas.height * contentWidth) / svgCanvas.width;
            
            if (svgHeight > pageHeight - margin * 2 - 40) {
              ensureSpace(100);
            } else {
              ensureSpace(svgHeight);
            }
            
            pdf.addImage(svgCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, svgHeight);
            currentY += svgHeight + 20;
          } catch (e) { console.error('Mermaid PDF error:', e); }
        } else if (part.startsWith('```')) {
          const code = part.replace(/```(?:\w+)?\n([\s\S]*?)```/, '$1').trim();
          // Split code into chunks if too long
          const codeLines = code.split('\n');
          const chunkSize = 50;
          for (let j = 0; j < codeLines.length; j += chunkSize) {
            const chunk = codeLines.slice(j, j + chunkSize).join('\n');
            const codeDiv = document.createElement('div');
            codeDiv.style.padding = '10px 40px';
            codeDiv.style.width = '800px';
            codeDiv.style.boxSizing = 'border-box';
            codeDiv.innerHTML = `
              <pre style="background: #f8fafc; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; color: #334155; font-size: 11px; font-family: monospace; white-space: pre-wrap; word-break: break-all; margin: 0;">${chunk}</pre>
            `;
            
            tempContainer.innerHTML = '';
            tempContainer.appendChild(codeDiv);
            const codeCanvas = await html2canvas(codeDiv, { scale: 1.5, useCORS: true });
            const codeHeight = (codeCanvas.height * contentWidth) / codeCanvas.width;
            ensureSpace(codeHeight);
            pdf.addImage(codeCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, codeHeight);
            currentY += codeHeight + 5;
          }
          currentY += 10;
        } else {
          // Split text into paragraphs to avoid massive canvases
          const paragraphs = part.split('\n\n');
          for (const p of paragraphs) {
            if (!p.trim()) continue;
            const textDiv = document.createElement('div');
            textDiv.style.padding = '5px 40px';
            textDiv.style.width = '800px';
            textDiv.style.boxSizing = 'border-box';
            textDiv.style.fontSize = '14px';
            textDiv.style.lineHeight = '1.7';
            textDiv.style.color = '#334155';
            
            let html = p
              .replace(/^# (.*$)/gm, '<h1 style="font-size: 22px; font-weight: 800; color: #0f172a; margin: 20px 0 10px;">$1</h1>')
              .replace(/^## (.*$)/gm, '<h2 style="font-size: 20px; font-weight: 800; color: #0f172a; margin: 18px 0 8px;">$1</h2>')
              .replace(/^### (.*$)/gm, '<h3 style="font-size: 18px; font-weight: 800; color: #0f172a; margin: 15px 0 5px;">$1</h3>')
              .replace(/^\* (.*$)/gm, '<li style="margin-left: 20px;">$1</li>')
              .replace(/^- (.*$)/gm, '<li style="margin-left: 20px;">$1</li>')
              .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
              .replace(/\*(.*?)\*/g, '<em>$1</em>')
              .replace(/`(.*?)`/g, '<code style="background: #f1f5f9; padding: 2px 4px; border-radius: 4px; font-family: monospace;">$1</code>')
              .replace(/\n/g, '<br/>');
            
            textDiv.innerHTML = html;
            
            tempContainer.innerHTML = '';
            tempContainer.appendChild(textDiv);
            const textCanvas = await html2canvas(textDiv, { scale: 1.5, useCORS: true });
            const textHeight = (textCanvas.height * contentWidth) / textCanvas.width;
            
            ensureSpace(textHeight);
            pdf.addImage(textCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, textHeight);
            currentY += textHeight + 5;
          }
          currentY += 10;
        }
      }

      // Category Scores
      if (type === 'analysis' && (parsedPhases.indexOf(phase) === 12 || parsedPhases.indexOf(phase) === parsedPhases.length - 1) && currentAnalysis.categoryScores) {
        const scoresDiv = document.createElement('div');
        scoresDiv.style.padding = '20px 40px';
        scoresDiv.style.width = '800px';
        scoresDiv.style.boxSizing = 'border-box';
        scoresDiv.style.display = 'grid';
        scoresDiv.style.gridTemplateColumns = 'repeat(2, 1fr)';
        scoresDiv.style.gap = '20px';
        Object.entries(currentAnalysis.categoryScores).forEach(([cat, score]) => {
          const div = document.createElement('div');
          div.style.padding = '20px';
          div.style.backgroundColor = '#f8fafc';
          div.style.border = '1px solid #e2e8f0';
          div.style.borderRadius = '16px';
          const color = (score as number) >= 80 ? '#10b981' : (score as number) >= 60 ? '#f59e0b' : '#ef4444';
          div.innerHTML = `
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
              <span style="font-size: 14px; font-weight: 800; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px;">${cat}</span>
              <span style="font-size: 20px; font-weight: 900; color: ${color};">${score}/100</span>
            </div>
            <div style="height: 8px; width: 100%; background: #e2e8f0; border-radius: 9999px; overflow: hidden;">
              <div style="height: 100%; width: ${score}%; background: ${color};"></div>
            </div>
          `;
          scoresDiv.appendChild(div);
        });
        
        tempContainer.innerHTML = '';
        tempContainer.appendChild(scoresDiv);
        const scoresCanvas = await html2canvas(scoresDiv, { scale: 1.5, useCORS: true });
        const scoresHeight = (scoresCanvas.height * contentWidth) / scoresCanvas.width;
        ensureSpace(scoresHeight);
        pdf.addImage(scoresCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, scoresHeight);
        currentY += scoresHeight + 20;
      }
    }

    // Add File Tree
    if (type === 'analysis' && currentAnalysis.fileTree?.length) {
      toast.loading('Finalizing file structure...', { id: loadingToast });
      const treeDiv = document.createElement('div');
      treeDiv.style.padding = '40px';
      treeDiv.style.width = '800px';
      treeDiv.style.boxSizing = 'border-box';
      treeDiv.innerHTML = `
        <h2 style="font-size: 28px; font-weight: 900; color: #0f172a; margin-bottom: 25px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; letter-spacing: -0.5px;">Repository File Structure</h2>
      `;
      tempContainer.innerHTML = '';
      tempContainer.appendChild(treeDiv);
      const treeTitleCanvas = await html2canvas(treeDiv, { scale: 1.5, useCORS: true });
      const treeTitleHeight = (treeTitleCanvas.height * contentWidth) / treeTitleCanvas.width;
      ensureSpace(treeTitleHeight);
      pdf.addImage(treeTitleCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, treeTitleHeight);
      currentY += treeTitleHeight + 10;

      const treeLines = currentAnalysis.fileTree;
      const treeChunkSize = 60;
      for (let j = 0; j < treeLines.length; j += treeChunkSize) {
        const chunk = treeLines.slice(j, j + treeChunkSize).join('\n');
        const chunkDiv = document.createElement('div');
        chunkDiv.style.padding = '10px 40px';
        chunkDiv.style.width = '800px';
        chunkDiv.style.boxSizing = 'border-box';
        chunkDiv.innerHTML = `
          <pre style="font-size: 11px; background: #f8fafc; padding: 25px; border: 1px solid #e2e8f0; border-radius: 16px; color: #334155; line-height: 1.5; font-family: monospace; white-space: pre-wrap; word-break: break-all; margin: 0;">${chunk}</pre>
        `;
        tempContainer.innerHTML = '';
        tempContainer.appendChild(chunkDiv);
        const chunkCanvas = await html2canvas(chunkDiv, { scale: 1.5, useCORS: true });
        const chunkHeight = (chunkCanvas.height * contentWidth) / chunkCanvas.width;
        ensureSpace(chunkHeight);
        pdf.addImage(chunkCanvas.toDataURL('image/jpeg', 0.8), 'JPEG', margin, currentY, contentWidth, chunkHeight);
        currentY += chunkHeight + 5;
      }
    }

    // Final Footer
    addFooter(pdf.getNumberOfPages());

    const filename = `${currentAnalysis.repoName.replace(/\//g, '-')}-${type}-industry-standard.pdf`;
    pdf.save(filename);
    
    document.body.removeChild(tempContainer);
    toast.success('Professional PDF report generated!', { id: loadingToast });
  } catch (error) {
    console.error(error);
    toast.error('Failed to generate PDF. The repository might be too large.', { id: loadingToast });
  }
};
